import { defineConfig } from "vitepress";
import llmstxt from "vitepress-plugin-llms";
import { fontPreloadHead } from "./font-head.mjs";
import { renderMermaidDiagrams } from "./mermaid-markdown.mjs";
import { flattenedSidebar, nav, sidebar } from "./navigation.mjs";
import { resolveSwiftRelease } from "./release.mjs";
import { socialHead } from "./social-head.mjs";

/**
 * The site is published under `skeswa.github.io/cog/`, sharing that one
 * GitHub Pages deployment with the DocC API reference. `base` therefore has to
 * agree with the `--hosting-base-path cog` the DocC archive is built with
 * (`mise run docs:api`); the two halves are merged into a single artifact by
 * `tools/assemble-docs-site.mjs`.
 *
 * Both values are overridable so the assembled site can be served from a
 * scratch directory at a different prefix while checking it locally.
 */
const base = process.env.VITEPRESS_BASE ?? "/cog/";
const siteUrl = process.env.VITEPRESS_SITE_URL ?? "https://skeswa.github.io/cog/";
const swiftRelease = resolveSwiftRelease();

/** A `docs/public/` file as a URL, since `base` may be overridden without one. */
const asset = (name) => `${base.endsWith("/") ? base : `${base}/`}${name}`;

export default defineConfig({
  lang: "en-US",
  title: "Cog",
  titleTemplate: ":title · Cog",
  description:
    "Cog is a fine-grained state-management project for native mobile UI: a Swift library for SwiftUI and a Kotlin library for Jetpack Compose.",
  base,
  cleanUrls: true,

  // These two files are browsed directly on GitHub as often as they are read
  // here, so they stay named `README.md` in the tree and become directory
  // indexes only on the site.
  rewrites: {
    "swift/README.md": "swift/index.md",
    "kotlin/README.md": "kotlin/index.md",
  },

  // Scoped to the DocC half of the site and nothing else. Those routes are
  // real, but they are produced by `mise run docs:api` and only join this
  // output when `tools/assemble-docs-site.mjs` merges the two — VitePress
  // cannot see them at build time and would call every one of them dead. The
  // check stays on everywhere else, because a genuinely broken cross-document
  // link is exactly the failure this site exists to catch. The merge script
  // asserts these routes actually arrived.
  ignoreDeadLinks: [/^\/documentation\//],

  markdown: {
    config: renderMermaidDiagrams,
  },

  sitemap: { hostname: siteUrl },
  // The font preloads come first because they are the only entries here that
  // race the render: the sooner the scanner sees them the less of the page is
  // painted in the fallback. `socialHead` returns nothing for the 404 page,
  // which still wants the font.
  transformHead: (context) => [...fontPreloadHead(context.assets), ...socialHead(context, siteUrl)],

  vite: {
    define: {
      __COG_SWIFT_RELEASE__: JSON.stringify(swiftRelease),
    },
    // The agent-readable twin of the site. Coding agents fetch HTML badly:
    // the rendered page is an app shell plus chrome, and a client-rendered
    // route is empty to a fetcher that runs no JavaScript. This plugin writes
    // three things into the build output beside the HTML: `llms.txt`, the
    // index that Cursor, Claude Code, Copilot, and Cline request first when
    // pointed at a docs site; `llms-full.txt`, every page in one file; and a
    // `.md` twin of every route, so `/swift/agent-guide.md` is the page's own
    // Markdown. It also adds a hidden hint on each page that names the twin.
    // Links inside the generated files carry the site origin because agents
    // cannot resolve relative Markdown links against a page they fetched; the
    // plugin appends `base` itself, so `domain` is the origin alone. The
    // sidebar it is given is flattened for the reason `flattenedSidebar`
    // explains.
    plugins: [
      llmstxt({
        domain: new URL(siteUrl).origin,
        sidebar: flattenedSidebar(),
        title: "Cog",
        description:
          "Fine-grained state management for native mobile UI: a Swift library for SwiftUI and a designed Kotlin library for Jetpack Compose.",
        details:
          "Start with /swift/agent-guide.md, the one-page brief for coding agents. The handbook chapters under /swift/handbook/ are the full conventions.",
      }),
    ],
  },

  head: [
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "Cog" }],
    ["meta", { property: "og:locale", content: "en_US" }],
    ["meta", { name: "theme-color", content: "#0b0b10" }],

    // Head links are not rewritten with `base`, so they carry it themselves.
    // The raster is listed before the vector deliberately: a browser that
    // understands `image/svg+xml` prefers it regardless of order, and one that
    // does not needs to have already seen a PNG it can use. All three are
    // generated by `mise run docs:mark` from the same gear geometry as the
    // navigation-bar mark.
    ["link", { rel: "icon", type: "image/png", sizes: "96x96", href: asset("favicon-96.png") }],
    ["link", { rel: "icon", type: "image/svg+xml", href: asset("favicon.svg") }],
    ["link", { rel: "apple-touch-icon", sizes: "180x180", href: asset("apple-touch-icon.png") }],
  ],

  themeConfig: {
    siteTitle: "Cog",
    nav,
    sidebar,
    outline: { level: [2, 3] },
    search: { provider: "local" },
    editLink: {
      pattern: "https://github.com/skeswa/cog/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/skeswa/cog" }],
    footer: {
      message: "Released under the MIT License.",
      copyright: "Copyright © 2026 Sandile Keswa",
    },
  },
});
